package com.clanhq.verifier;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.ConfigSection;

@ConfigGroup(ClanHQVerifierConfig.GROUP)
public interface ClanHQVerifierConfig extends Config
{
    String GROUP = "clanhqVerifier";

    @ConfigSection(
        name = "Features",
        description = "ClanHQ tools available in the side panel",
        position = -1)
    String FEATURES_SECTION = "features";

    @ConfigItem(
        keyName = "eventsEnabled",
        name = "Events",
        description = "Join and display ClanHQ competitions",
        section = FEATURES_SECTION,
        position = 1)
    default boolean eventsEnabled()
    {
        return true;
    }

    @ConfigItem(
        keyName = "bingoEnabled",
        name = "Bingo",
        description = "Load the active Bingo board and submit eligible Loot Tracker events",
        section = FEATURES_SECTION,
        position = 2)
    default boolean bingoEnabled()
    {
        return false;
    }

    @ConfigItem(
        keyName = "dailyTasksEnabled",
        name = "Daily Tasks",
        description = "View and claim ClanHQ currency daily tasks",
        section = FEATURES_SECTION,
        position = 3)
    default boolean dailyTasksEnabled()
    {
        return true;
    }

    @ConfigItem(
        keyName = "bingoScreenshotsEnabled",
        name = "Bingo screenshots",
        description = "Attach a watermarked gameplay screenshot to Bingo drops",
        section = FEATURES_SECTION,
        position = 4)
    default boolean bingoScreenshotsEnabled()
    {
        return false;
    }

    @ConfigItem(
        keyName = "showDripDropsBalance",
        name = "Show currency balance",
        description = "Show your private configured currency balance on Overview",
        section = FEATURES_SECTION,
        position = 5)
    default boolean showCurrencyBalance()
    {
        return true;
    }

    @ConfigSection(
        name = "ClanHQ connection",
        description = "Where review evidence will be submitted",
        position = 0)
    String CONNECTION_SECTION = "connection";

    @ConfigSection(
        name = "Clan event",
        description = "Join a competition created by ClanHQ",
        position = 1)
    String EVENT_SECTION = "event";

    @ConfigSection(
        name = "Bingo",
        description = "Connect to a ClanHQ Bingo event",
        position = 2)
    String BINGO_SECTION = "bingo";

    @ConfigItem(
        keyName = "apiBaseUrl",
        name = "ClanHQ API URL",
        description = "HTTPS destination supplied by your clan; localhost HTTP is allowed for development",
        section = CONNECTION_SECTION,
        position = 0)
    default String apiBaseUrl()
    {
        return "";
    }

    @ConfigItem(
        keyName = "installationToken",
        name = "Installation token",
        description = "Unique revocable token created automatically during pairing",
        section = CONNECTION_SECTION,
        secret = true,
        position = 1)
    default String installationToken()
    {
        return "";
    }

    @ConfigItem(
        keyName = "pairingCode",
        name = "Pairing code",
        description = "One-time code generated by /plugin pair in Discord",
        section = CONNECTION_SECTION,
        secret = true,
        position = 2)
    default String pairingCode()
    {
        return "";
    }

    @ConfigItem(
        keyName = "installationLabel",
        name = "Device name",
        description = "A recognizable name for this RuneLite installation",
        section = CONNECTION_SECTION,
        position = 3)
    default String installationLabel()
    {
        return "RuneLite";
    }

    @ConfigItem(
        keyName = "pendingInstallationToken",
        name = "Pending installation token",
        description = "Internal pairing retry state",
        section = CONNECTION_SECTION,
        hidden = true,
        secret = true,
        position = 4)
    default String pendingInstallationToken()
    {
        return "";
    }

    @ConfigItem(
        keyName = "eventCode",
        name = "Event code",
        description = "Code identified with a non-Bingo ClanHQ event",
        section = EVENT_SECTION,
        position = 0)
    default String eventCode()
    {
        return "";
    }

    @ConfigItem(
        keyName = "bingoEventCode",
        name = "Event code",
        description = "Code identified with the Bingo event; contact staff for support",
        section = BINGO_SECTION,
        position = 0)
    default String bingoEventCode()
    {
        return "";
    }
}
