package com.clanhq.verifier;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.ConfigSection;
import net.runelite.client.config.Range;

@ConfigGroup(ClanHQVerifierConfig.GROUP)
public interface ClanHQVerifierConfig extends Config
{
    String GROUP = "clanhqVerifier";

    enum DailyTasksDisplayMode
    {
        OVERLAY,
        INFO_BOXES
    }

    @ConfigSection(
        name = "Features",
        description = "ClanHQ tools available in the side panel",
        position = -1)
    String FEATURES_SECTION = "features";

    @ConfigItem(
        keyName = "eventsEnabled",
        name = "Events",
        description = "Join and display ClanHQ competitions",
        section = FEATURES_SECTION,
        position = 1)
    default boolean eventsEnabled()
    {
        return true;
    }

    @ConfigItem(
        keyName = "bingoEnabled",
        name = "Bingo",
        description = "Load the active Bingo board and submit eligible Loot Tracker events",
        section = FEATURES_SECTION,
        position = 2)
    default boolean bingoEnabled()
    {
        return false;
    }

    @ConfigItem(
        keyName = "dailyTasksEnabled",
        name = "Tasks",
        description = "View and claim ClanHQ currency daily tasks",
        section = FEATURES_SECTION,
        position = 3)
    default boolean dailyTasksEnabled()
    {
        return true;
    }

    @ConfigItem(
        keyName = "bingoScreenshotsEnabled",
        name = "Bingo screenshots",
        description = "Attach a watermarked gameplay screenshot to Bingo drops",
        section = FEATURES_SECTION,
        position = 4)
    default boolean bingoScreenshotsEnabled()
    {
        return false;
    }

    @ConfigItem(
        keyName = "gearAdvisorEnabled",
        name = "Gear Advisor",
        description = "Build personalized OSRS loadouts from your verified Character Sync data",
        section = FEATURES_SECTION,
        position = 5)
    default boolean gearAdvisorEnabled()
    {
        return true;
    }

    @ConfigSection(
        name = "Task overlay",
        description = "Customize the in-game daily task display",
        position = 0)
    String TASK_OVERLAY_SECTION = "taskOverlay";

    @ConfigItem(
        keyName = "dailyTasksOverlay",
        name = "Show overlay",
        description = "Show today's ClanHQ task progress in the game overlay",
        section = TASK_OVERLAY_SECTION,
        position = 0)
    default boolean dailyTasksOverlay()
    {
        return true;
    }

    @ConfigItem(
        keyName = "dailyTasksDisplayMode",
        name = "Display mode",
        description = "Choose between the compact task overlay and RuneLite info boxes",
        section = TASK_OVERLAY_SECTION,
        position = 1)
    default DailyTasksDisplayMode dailyTasksDisplayMode()
    {
        return DailyTasksDisplayMode.OVERLAY;
    }

    @Range(min = 0, max = 255)
    @ConfigItem(
        keyName = "dailyTasksOverlayOpacity",
        name = "Opacity",
        description = "Background opacity (0 is transparent, 255 is opaque)",
        section = TASK_OVERLAY_SECTION,
        position = 2)
    default int dailyTasksOverlayOpacity()
    {
        return 220;
    }

    @ConfigSection(
        name = "ClanHQ connection",
        description = "Where review evidence will be submitted",
        position = 1)
    String CONNECTION_SECTION = "connection";

    @ConfigSection(
        name = "Bingo",
        description = "Connect to the active ClanHQ Bingo event",
        position = 2)
    String BINGO_SECTION = "bingo";

    @ConfigItem(
        keyName = "apiBaseUrl",
        name = "ClanHQ API URL",
        description = "HTTPS destination supplied by your clan; localhost HTTP is allowed for development",
        section = CONNECTION_SECTION,
        position = 0)
    default String apiBaseUrl()
    {
        return "";
    }

    @ConfigItem(
        keyName = "installationToken",
        name = "Installation token",
        description = "Unique revocable token created automatically during pairing",
        section = CONNECTION_SECTION,
        secret = true,
        position = 1)
    default String installationToken()
    {
        return "";
    }

    @ConfigItem(
        keyName = "pairingCode",
        name = "Pairing code",
        description = "One-time code generated by /plugin pair in Discord",
        section = CONNECTION_SECTION,
        secret = true,
        position = 2)
    default String pairingCode()
    {
        return "";
    }

    @ConfigItem(
        keyName = "installationLabel",
        name = "Device name",
        description = "A recognizable name for this RuneLite installation",
        section = CONNECTION_SECTION,
        position = 3)
    default String installationLabel()
    {
        return "RuneLite";
    }

    @ConfigItem(
        keyName = "pendingInstallationToken",
        name = "Pending installation token",
        description = "Internal pairing retry state",
        section = CONNECTION_SECTION,
        hidden = true,
        secret = true,
        position = 4)
    default String pendingInstallationToken()
    {
        return "";
    }

}
